/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.salgen.View;

import com.salgen.Conttroller.Sales_Invoice_Controller;
import com.salgen.Model.Invoice;
import com.salgen.Model.Invoice_Table_Model;
import com.salgen.Model.Line_Table_Model;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Abdulrahman
 */
public class Sales_Invoice_Gen_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Sales_Invoice_Gen_Frame
     */
    public Sales_Invoice_Gen_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        invoicesTable.getSelectionModel().addListSelectionListener(controller);
        jScrollPane2 = new javax.swing.JScrollPane();
        linesTable = new javax.swing.JTable();
        AddNewInvoiceBtn = new javax.swing.JButton();
        AddNewInvoiceBtn.addActionListener(controller);
        deleteSelectedInvoiceBtn = new javax.swing.JButton();
        deleteSelectedInvoiceBtn.addActionListener(controller);
        AddNewLineBtn = new javax.swing.JButton();
        AddNewLineBtn.addActionListener(controller);
        deleteSelectedLineBtn = new javax.swing.JButton();
        deleteSelectedLineBtn.addActionListener(controller);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoiceNumberJlabel = new javax.swing.JLabel();
        invoiceDateJlabel = new javax.swing.JLabel();
        clientNameJlabel = new javax.swing.JLabel();
        invoiceTotalJlable = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadInvoicesMenuItem = new javax.swing.JMenuItem();
        loadInvoicesMenuItem.addActionListener(controller);
        saveInvoicesMenuItem = new javax.swing.JMenuItem();
        saveInvoicesMenuItem.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoicesTable);

        linesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(linesTable);

        AddNewInvoiceBtn.setText("Add New Invoice");
        AddNewInvoiceBtn.setToolTipText("");

        deleteSelectedInvoiceBtn.setText("Delete Invoice");

        AddNewLineBtn.setText("Add New Line");

        deleteSelectedLineBtn.setText("Delete Line");

        jLabel1.setText("Invoice Number : ");

        jLabel2.setText("Invoice Date :");

        jLabel3.setText("Client Name : ");

        jLabel4.setText("Total of Invoice : ");

        jMenu1.setText("File");

        loadInvoicesMenuItem.setText("Load Invoices");
        loadInvoicesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadInvoicesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadInvoicesMenuItem);

        saveInvoicesMenuItem.setText("Save Invoices");
        saveInvoicesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInvoicesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveInvoicesMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(AddNewInvoiceBtn)
                .addGap(115, 115, 115)
                .addComponent(deleteSelectedInvoiceBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddNewLineBtn)
                .addGap(132, 132, 132)
                .addComponent(deleteSelectedLineBtn)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoiceTotalJlable)
                            .addComponent(clientNameJlabel)
                            .addComponent(invoiceDateJlabel)
                            .addComponent(invoiceNumberJlabel))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invoiceNumberJlabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invoiceDateJlabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(clientNameJlabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invoiceTotalJlable))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewInvoiceBtn)
                    .addComponent(deleteSelectedInvoiceBtn)
                    .addComponent(AddNewLineBtn)
                    .addComponent(deleteSelectedLineBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadInvoicesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadInvoicesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadInvoicesMenuItemActionPerformed

    private void saveInvoicesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInvoicesMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveInvoicesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Invoice_Gen_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Invoice_Gen_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Invoice_Gen_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Invoice_Gen_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Invoice_Gen_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewInvoiceBtn;
    private javax.swing.JButton AddNewLineBtn;
    private javax.swing.JLabel clientNameJlabel;
    private javax.swing.JButton deleteSelectedInvoiceBtn;
    private javax.swing.JButton deleteSelectedLineBtn;
    private javax.swing.JLabel invoiceDateJlabel;
    private javax.swing.JLabel invoiceNumberJlabel;
    private javax.swing.JLabel invoiceTotalJlable;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable linesTable;
    private javax.swing.JMenuItem loadInvoicesMenuItem;
    private javax.swing.JMenuItem saveInvoicesMenuItem;
    // End of variables declaration//GEN-END:variables
    private ArrayList <Invoice> invoices = new ArrayList<>();
    private Sales_Invoice_Controller controller = new Sales_Invoice_Controller(this) ;
    private Invoice_Table_Model invoice_Table_Model ;
    private Line_Table_Model line_Table_Model ;
    
    
  /**************************** Getter and setter for invoice & line table Models ***************************************/

    public Invoice_Table_Model getInvoice_Table_Model() {
        return invoice_Table_Model;
    }

    public void setInvoice_Table_Model(Invoice_Table_Model invoice_Table_Model) {
        this.invoice_Table_Model = invoice_Table_Model;
    }

    public Line_Table_Model getLine_Table_Model() {
        return line_Table_Model;
    }

    public void setLine_Table_Model(Line_Table_Model line_Table_Model) {
        this.line_Table_Model = line_Table_Model;
    }
    

    
    
    // Getter and Setter of the Array of Invoices 
    
    public ArrayList<Invoice> getInvoices() {
        return invoices;
    }

    public void setInvoices(ArrayList<Invoice> invoices) {
        this.invoices = invoices;
    }
    
    // Getter and Setter of invoices Table
    
    public JTable getInvoicesTable() {
        return invoicesTable;
    }

    public void setInvoicesTable(JTable invoicesTable) {
        this.invoicesTable = invoicesTable;
    }

    // Getter and Setter of Line Table
    
    public JTable getLinesTable() {
        return linesTable;
    }

    public void setLinesTable(JTable linesTable) {
        this.linesTable = linesTable;
    }
    
    // Getter and Setter of Client Name Label

    public JLabel getClientNameJlabel() {
        return clientNameJlabel;
    }

    public void setClientNameJlabel(JLabel clientNameJlabel) {
        this.clientNameJlabel = clientNameJlabel;
    }
    
    // Getter and Setter of Invoice Date Label

    public JLabel getInvoiceDateJlabel() {
        return invoiceDateJlabel;
    }

    public void setInvoiceDateJlabel(JLabel invoiceDateJlabel) {
        this.invoiceDateJlabel = invoiceDateJlabel;
    }
  
    // Getter and Setter of Invoice Number Label
    
    public JLabel getInvoiceNumberJlabel() {
        return invoiceNumberJlabel;
    }

    public void setInvoiceNumberJlabel(JLabel invoiceNumberJlabel) {
        this.invoiceNumberJlabel = invoiceNumberJlabel;
    }

   // Getter and Setter of Total of Invoice Label

    public JLabel getInvoiceTotalJlable() {
        return invoiceTotalJlable;
    }

    public void setInvoiceTotalJlable(JLabel invoiceTotalJlable) {
        this.invoiceTotalJlable = invoiceTotalJlable;
    }


    // Getter and setter of Listner of the frame

    public Sales_Invoice_Controller getController() {
        return controller;
    }
    
    
    // Get the number of the next invoice to add to the new created invoice
    
    public int getNextInvoiceNum ()
    {
        int num =  0 ;
        
        for(Invoice invoice : invoices)
        {
            if(invoice.getInvoiceNumber()> num )
            {
                num = invoice.getInvoiceNumber();
            }
        }
        return (num+1) ;
    }
    
    

}
